Change lifetime for DbContext from Scoped to Transient
Nested GraphQL queries are executed in parallel.
As result, if the same instance of DbContext is shared between these queries, the following error could occur:

An exception occurred while iterating over the results of a query for context type 'MusicLibraryApi.Dal.EfCore.MusicLibraryDbContext'.
System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

There is a solution with serial execution strategy, described here - https://github.com/graphql-dotnet/graphql-dotnet/issues/863#issuecomment-468981901
This approach devalues the DataLoader, since the queries will not be batched, i.e. there will be N batch queries with collection of single id.
This issue is reported here - https://github.com/graphql-dotnet/graphql-dotnet/issues/1191

So, for this moment the only viable solution is to use transient DbContext lifetime.